version: "2"
run:
  modules-download-mode: readonly
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - forbidigo
    - forcetypeassert
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          allow:
            - $gostd
            - github.com/NVIDIA
            - github.com/go-logr/logr
            - k8s.io
            - sigs.k8s.io
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 58
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - appendAssign
    gocyclo:
      min-complexity: 30
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
    lll:
      line-length: 120
    misspell:
      locale: US
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo
        - github.com/onsi/ginkgo/extensions/table
        - github.com/onsi/gomega
        - github.com/onsi/gomega/gstruct
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/k8s-operator-libs
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
