/*
Copyright 2022 NVIDIA CORPORATION & AFFILIATES
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	mock "github.com/stretchr/testify/mock"

	base "github.com/NVIDIA/k8s-operator-libs/pkg/upgrade/base"

	v1 "k8s.io/api/apps/v1"
)

// PodManager is an autogenerated mock type for the PodManager type
type PodManager struct {
	mock.Mock
}

// GetDaemonsetControllerRevisionHash provides a mock function with given fields: ctx, daemonset
func (_m *PodManager) GetDaemonsetControllerRevisionHash(ctx context.Context, daemonset *v1.DaemonSet) (string, error) {
	ret := _m.Called(ctx, daemonset)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *v1.DaemonSet) string); ok {
		r0 = rf(ctx, daemonset)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.DaemonSet) error); ok {
		r1 = rf(ctx, daemonset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPodControllerRevisionHash provides a mock function with given fields: ctx, pod
func (_m *PodManager) GetPodControllerRevisionHash(ctx context.Context, pod *corev1.Pod) (string, error) {
	ret := _m.Called(ctx, pod)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Pod) string); ok {
		r0 = rf(ctx, pod)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Pod) error); ok {
		r1 = rf(ctx, pod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPodDeletionFilter provides a mock function with given fields:
func (_m *PodManager) GetPodDeletionFilter() base.PodDeletionFilter {
	ret := _m.Called()

	var r0 base.PodDeletionFilter
	if rf, ok := ret.Get(0).(func() base.PodDeletionFilter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(base.PodDeletionFilter)
		}
	}

	return r0
}

// ScheduleCheckOnPodCompletion provides a mock function with given fields: ctx, config
func (_m *PodManager) ScheduleCheckOnPodCompletion(ctx context.Context, config *base.PodManagerConfig) error {
	ret := _m.Called(ctx, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *base.PodManagerConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SchedulePodEviction provides a mock function with given fields: ctx, config
func (_m *PodManager) SchedulePodEviction(ctx context.Context, config *base.PodManagerConfig) error {
	ret := _m.Called(ctx, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *base.PodManagerConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SchedulePodsRestart provides a mock function with given fields: ctx, pods
func (_m *PodManager) SchedulePodsRestart(ctx context.Context, pods []*corev1.Pod) error {
	ret := _m.Called(ctx, pods)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*corev1.Pod) error); ok {
		r0 = rf(ctx, pods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPodManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewPodManager creates a new instance of PodManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPodManager(t mockConstructorTestingTNewPodManager) *PodManager {
	mock := &PodManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
