//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradePolicySpec) DeepCopyInto(out *DriverUpgradePolicySpec) {
	*out = *in
	if in.PodDeletion != nil {
		in, out := &in.PodDeletion, &out.PodDeletion
		*out = new(PodDeletionSpec)
		**out = **in
	}
	if in.WaitForCompletion != nil {
		in, out := &in.WaitForCompletion, &out.WaitForCompletion
		*out = new(WaitForCompletionSpec)
		**out = **in
	}
	if in.DrainSpec != nil {
		in, out := &in.DrainSpec, &out.DrainSpec
		*out = new(DrainSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradePolicySpec.
func (in *DriverUpgradePolicySpec) DeepCopy() *DriverUpgradePolicySpec {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverUpgradePolicySpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
